version: '2'

services:

  #PGSQL
  database:
    build:
      context: .
      dockerfile: Dockerfile-Pgsql

    image: loadtest-pgsql-9.5
    container_name: loadtest-pgsql-container
        
    volumes:
      - ../../database/pgsql/data:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Dockerfile-LoadTest
      
    image: loadtest-dotnet
    container_name: loadtest-dotnet-container

    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

    links:
      - database

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-Nginx-Proxy

    image: loadtest-nginx-proxy-dotnet
    container_name: loadtest-nginx-proxy-dotnet-container

    ports:
      - "80:80"

    links:
      - webapi

    privileged: true

    command: bash -c "echo '1024 65535' > /proc/sys/net/ipv4/ip_local_port_range && echo '1024' > /proc/sys/net/core/somaxconn && service nginx start"