version: '2'

services:
 
  #MYSQL
  database:
    build:
      context: .
      dockerfile: Dockerfile-Mysql

    image: loadtest-mysql-5.7.17
    container_name: loadtest-mysql-container
    
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    volumes:
      - ../../database/mysql/data:/var/lib/mysql

  webapi:
    build:
      context: .
      dockerfile: Dockerfile-LoadTest
      
    image: loadtest-dotnet
    container_name: loadtest-dotnet-container

    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

    links:
      - database

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-Nginx-Proxy

    image: loadtest-nginx-proxy-dotnet
    container_name: loadtest-nginx-proxy-dotnet-container

    ports:
      - "80:80"

    links:
      - webapi

    privileged: true

    command: bash -c "echo '1024 65535' > /proc/sys/net/ipv4/ip_local_port_range && echo '1024' > /proc/sys/net/core/somaxconn && service nginx start"