version: '2'

services:

  #PGSQL
  database:
    build:
      context: .
      dockerfile: Dockerfile-Pgsql

    image: loadtest-pgsql-9.5
    container_name: loadtest-pgsql-container
        
    volumes:
      - ../../database/pgsql/data:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Dockerfile-LoadTest
      
    image: loadtest-nodejs
    container_name: loadtest-nodejs-container

    environment:
      - NODE_ENV=staging

    links:
      - database

    expose:

      - "5051"
      
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-Nginx-Proxy
    
    image: loadtest-nginx-proxy-nodejs
    container_name: loadtest-nginx-proxy-nodejs-container
       
    ports:
      - "8081:8081"

    links:
      - webapi

    privileged: true

    command: bash -c "echo '1024 65535' > /proc/sys/net/ipv4/ip_local_port_range && echo '1024' > /proc/sys/net/core/somaxconn && service nginx start"
